repos:
- repo: local
  hooks:
    - id: trufflehog
      name: TruffleHog
      description: Detect secrets in your data.
      entry: bash -c 'trufflehog ./ --max_depth=2'
      language: system
      stages: ["commit", "push"]