channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::numpy=2.0.0
  - conda-forge::matplotlib=3.8.4
  - conda-forge::gdal=3.9.1
  - conda-forge::requests=2.32.3
  - conda-forge::geopandas=1.0.1
  - conda-forge::shapely=2.0.4
  - conda-forge::ipykernel=6.29.5
  - conda-forge::hydra-core=1.3.2
  - conda-forge::imageio=2.34.2
  - pip