dependencies:
  - conda-forge::python=3.9
  - conda-forge::gdal=3.9.2
  - pip
  - pip:
    - tensordict==0.5.0
    - torch==2.4.0
    - torchvision==0.19.0
    - torchaudio==2.4.0
    - numpy==2.0.0
    - matplotlib==3.8.4
    - requests==2.32.3
    - geopandas==1.0.1
    - pyogrio==0.9.0
    - shapely==2.0.4
    - ipykernel==6.29.5
    - hydra-core==1.3.2
    - imageio==2.34.2
    - cdsapi==0.7.0
    - pre-commit==3.7.1
    - aiohttp==3.9.5
    - mypy==1.11.1
    - loguru==0.7.2
    - psutil==6.0.0
    - scikit-learn==1.5.1
    - torchmetrics==1.4.1
    - torchinfo==1.8.0
    - tqdm==4.66.5
    - comet-ml==3.44.4
    - segmentation-models-pytorch==0.3.4