dependencies:
  - conda-forge::python=3.9
  - conda-forge::numpy=2.0.0
  - conda-forge::matplotlib=3.8.4
  - conda-forge::gdal=3.9.2
  - conda-forge::requests=2.32.3
  - conda-forge::geopandas=1.0.1
  - conda-forge::pyogrio=0.9.0
  - conda-forge::shapely=2.0.4
  - conda-forge::ipykernel=6.29.5
  - conda-forge::hydra-core=1.3.2
  - conda-forge::imageio=2.34.2
  - conda-forge::cdsapi=0.7.0
  - conda-forge::pre-commit=3.7.1
  - conda-forge::aiohttp=3.9.5
  - conda-forge::mypy=1.11.1
  - conda-forge::loguru=0.7.2
  - conda-forge::psutil=6.0.0
  - conda-forge::scikit-learn=1.5.1
  - conda-forge::torchmetrics=1.4.0.post0
  - conda-forge::torchinfo=1.8.0
  - pytorch::pytorch=2.4.0
  - pytorch::torchvision=0.19.0
  - pytorch::torchaudio=2.4.0
  - pytorch::cpuonly
  #- ndvidia::pytorch-cuda=12.1
  - pip