channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::numpy=2.0.0
  - conda-forge::matplotlib=3.8.4
  - conda-forge::gdal=3.9.1
  - conda-forge::requests=2.32.3
  - conda-forge::geopandas=1.0.1
  - conda-forge::pyogrio=0.9.0
  - conda-forge::shapely=2.0.4
  - conda-forge::ipykernel=6.29.5
  - conda-forge::hydra-core=1.3.2
  - conda-forge::imageio=2.34.2
  - conda-forge::cdsapi=0.7.0
  - conda-forge::pre-commit=3.7.1
  - conda-forge::trufflehog=2.2.1
  - conda-forge::aiohttp=3.9.5
  - conda-forge::mypy=1.11.1
  - pip