debug: true
periods:
  target_year_start_inclusive: 2001
  target_year_end_inclusive: 2002
  month_start_inclusive: 5
  month_end_inclusive: 6
  target_period_length_in_years: 1
  input_data_affected_by_fires_period_length_in_years: 1
boundaries:
  output_path: "data/canada_boundary/"
  provinces: ["NL", "PE", "NS", "NB", "QC", "ON", "MB", "SK", "AB", "BC"]
resolution:
  pixel_size_in_meters: 250
  tile_size_in_pixels: 512
  resample_algorithm_continuous: "lanczos"
  resample_algorithm_categorical: "nearest"
projections:
  source_srs: 4326
  target_srs: 3978
paths:
  input_folder_path: "data/download/"
  output_folder_path: "data/datasets/"
sources:
    dynamic:
      era5_reanalysis_100m_u_component_of_wind:
        layer: ""
        aggregate_by: "average"
        data_type: "continuous"
        is_affected_by_fires: false
      era5_reanalysis_100m_v_component_of_wind:
        layer: ""
        aggregate_by: "average"
        data_type: "continuous"
        is_affected_by_fires: false
      # era5_reanalysis_2m_temperature:
      #   layer: ""
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: false
      # era5_reanalysis_potential_evaporation:
      #   layer: ""
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: false
      # era5_reanalysis_surface_net_solar_radiation:
      #   layer: ""
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: false
      # era5_reanalysis_surface_runoff:
      #   layer: ""
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: false
      # era5_reanalysis_total_precipitation:
      #   layer: ""
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: false
      # MOD13Q1_061__250m_16_days_NDVI:
      #   layer: "_250m_16_days_NDVI"
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: true
      # MOD13Q1_061__250m_16_days_EVI:
      #   layer: "_250m_16_days_EVI"
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: true
      # MOD44B_061_Percent_NonVegetated:
      #   layer: "Percent_NonVegetated"
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: true
      # MOD44B_061_Percent_NonTree_Vegetation:
      #   layer: "Percent_NonTree_Vegetation"
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: true
      # MOD44B_061_Percent_Tree_Cover:
      #   layer: "Percent_Tree_Cover"
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: true
      # MOD15A2H_061_Lai_500m:
      #   layer: "Lai_500m"
      #   aggregate_by: "average"
      #   data_type: "continuous"
      #   is_affected_by_fires: true
      # MOD44W_061_water_mask:
      #   layer: "water_mask"
      #   aggregate_by: "max"
      #   data_type: "categorical"
      #   is_affected_by_fires: true
      # MOD14A2_061_FireMask:
      #   layer: "FireMask"
      #   aggregate_by: "max"
      #   data_type: "categorical"
      #   is_affected_by_fires: true
    static:
      SRTMGL3_NC_003_SRTMGL3_DEM:
        layer: ""
        data_type: "continuous"
