periods:
  year_start_inclusive: 2001
  year_end_inclusive: 2002
  month_start_inclusive: 1
  month_end_inclusive: 12
boundaries:
  output_path: "data/canada_boundary/"
  provinces: ["NL", "PE", "NS", "NB", "QC", "ON", "MB", "SK", "AB", "BC"]
resolution:
  pixel_size_in_meters: 250
  tile_size_in_pixels: 512
  resample_algorithm: "bilinear"
projections:
  source_srs: 4326
  target_srs: 3978
paths:
  input_folder_path: "data/download/"
  output_folder_path: "data/processed/"
sources:
    dynamic:
      era5_reanalysis_100m_u_component_of_wind:
        layer: ""
        aggregate_by: "average"
      era5_reanalysis_100m_v_component_of_wind:
        layer: ""
        aggregate_by: "average"
      era5_reanalysis_2m_temperature:
        layer: ""
        aggregate_by: "average"
      era5_reanalysis_potential_evaporation:
        layer: ""
        aggregate_by: "average"
      era5_reanalysis_net_solar_radiation:
        layer: ""
        aggregate_by: "average"
      era5_reanalysis_surface_runoff:
        layer: ""
        aggregate_by: "average"
      era5_reanalysis_total_precipitation:
        layer: ""
        aggregate_by: "average"
      MOD13Q1_061_250m_16_days_NDVI:
        layer: "_250m_16_days_NDVI"
        aggregate_by: "average"
      MOD13Q1_061_250m_16_days_EVI:
        layer: "_250m_16_days_EVI"
        aggregate_by: "average"
      MOD44B_061_Percent_NonVegetated:
        layer: "Percent_NonVegetated"
        aggregate_by: "average"
      MOD44B_061_Percent_NonTree_Vegetation:
        layer: "Percent_NonTree_Vegetation"
        aggregate_by: "average"
      MOD44B_061_Percent_Tree_Cover:
        layer: "Percent_Tree_Cover"
        aggregate_by: "average"
      MOD15A2H_061_Lai_500m:
        layer: "Lai_500m"
        aggregate_by: "average"
      MOD44W_061_water_mask:
        layer: "water_mask"
        aggregate_by: "max"
      MOD14A2_061_FireMask:
        layer: "FireMask"
        aggregate_by: "max"
    static:
      NASADEM_NC_001_NASADEM_HGT:
        layer: "NASADEM_HGT"
