debug: false
seed: 42
run:
  name: "train_unet_${now:%Y-%m-%d_%H-%M-%S}"
model:
  number_of_input_channels: 2
  number_of_classes: 1
  activation_fn_name: "relu"
  num_encoder_decoder_blocks: 4
  use_batchnorm: false
  optimizer:
    name: "adam"
    lr: 0.001
output_path: "data/trainings/"
data:
  split_info_file_path: 'data/splits/holdout_split_2024-08-19_12-32-49/data_split_info.json'
  destination_no_data_value: -32768.0
  data_loading_num_workers: 1
  input_data_indexes_to_remove: []
training:
  max_nb_epochs: 1
  train_batch_size: 32
  eval_batch_size: 64
  optimization_metric_name: "dice_coef"
  minimize_optimization_metric: false
  loss: "bce_logits"
logging:
  loggers:
    - loguru
    # - comet_ml